---
- name: "join as a manager"
  shell: "docker swarm join --token {{ hostvars[first_manager_name]['manager_token']['stdout'] }} {{ hostvars[first_manager_name]['ansible_eth1']['ipv4']['address'] }}:2377"
  when: docker_info.stdout.find("Swarm{{':'}} inactive") != -1
  retries: 3
  delay: 20
