---

- name: "docker"
  firewalld:
    port: 2376/tcp
    immediate: true
    permanent: true
    state: enabled

- name: "docker"
  firewalld:
    port: 7946/tcp
    immediate: true
    permanent: true
    state: enabled

- name: "docker"
  firewalld:
    port: 7946/udp
    immediate: true
    permanent: true
    state: enabled

- name: "docker"
  firewalld:
    port: 4789/udp
    immediate: true
    permanent: true
    state: enabled



- name: "join as a worker"
  shell: "docker swarm join --token {{ hostvars[first_manager_name]['worker_token']['stdout'] }} {{ hostvars[first_manager_name]['ansible_eth1']['ipv4']['address'] }}:2377"
  when: "docker_info.stdout.find('Swarm: inactive') != -1"
  retries: 3
  delay: 20
